import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

import { Toaster } from '@/components/ui/sonner';
import { ConvexClientProvider } from '@/lib/convex-client-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ConvexClientProvider locale={locale}>
            <div className="h-full bg-slate-50">{children}</div>
            <Toaster />
          </ConvexClientProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
